# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.4-rhel
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /opt/opensearch-pod/data/app:Z
  creationTimestamp: "2024-10-14T08:50:15Z"
  labels:
    app: opensearch
  name: opensearch
spec:
  containers:
  - args:
    - opensearch-dashboards
    env:
    - name: OPENSEARCH_HOSTS
      value: https://127.0.0.1:9200
    image: docker.io/opensearchproject/opensearch-dashboards:2
    name: dashboard
    ports:
    - containerPort: 5601
      hostPort: 5601
    - containerPort: 9200
      hostPort: 9200
    securityContext:
      runAsNonRoot: true
  - args:
    - opensearch
    env:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: l%zglAd6Cc9p
    - name: node.store.allow_mmap
      value: "false"
    - name: cluster.initial_master_nodes
      value: os-node
    - name: bootstrap.memory_lock
      value: "false"
    - name: OPENSEARCH_JAVA_OPTS
      value: -Xms512m -Xmx512m
    - name: cluster.name
      value: os-cluster
    - name: node.name
      value: os-node
    image: docker.io/opensearchproject/opensearch:2
    name: app
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /usr/share/opensearch/data
      name: opt-opensearch-pod-data-app-host-0
    - mountPath: /usr/share/opensearch/plugins:Z
      name: opt-opensearch-pod-data-plugins-host-0
  volumes:
  - hostPath:
      path: /opt/opensearch-pod/data/app
      type: Directory
    name: opt-opensearch-pod-data-app-host-0
  - hostPath:
      path: /opt/opensearch-pod/data/plugins
      type: Directory
    name: opt-opensearch-pod-data-plugins-host-0

